dist: xenial
os: linux
git:
  depth: 3 

language: node_js
node_js:
  - 14
services:
  - docker
jobs:
  include: 
    # ======== Frontend ========
    - language: node_js
      node_js:  '14'

      warnings_are_errors: false

      before_install: 
        - cd 'Back-End DM'
        - cd dashboard-app
        - CI=false 

      branches:
        only:
          - master
          - feature/deployAPI

      install:
        - npm install

      script:
        - npm run build
        
       deploy:
        provider: script
        app: psique-dashboard
        script:
          - heroku container:login
          - heroku container:push web -a psique-dashboard
          - heroku container:release web -a psique-dashboard
        on: 
          repo: Daniel0205/Psique-DM
          branch: feature/deployAPI
    # ======== Parte del Backend ========
    - language: node_js
      node_js:  '14'

      warnings_are_errors: false

      before_install: 
        - cd 'Back-End DM'
 
      deploy:
        provider: script
        app: psique-dm
        script:
          - heroku container:login
          - heroku container:push web -a psique-dm
          - heroku container:release web -a psique-dm
        on: 
          repo: Daniel0205/Psique-DM
          branch: master