dist: xenial
os: linux
git:
  depth: 3 

language: node_js
node_js:
  - 14
services:
  - docker
jobs:
  include:
    # ======== Parte del frontend ========
    - language: node_js
      node_js:  '14'

      warnings_are_errors: false

      before_deploy: 
        - cd 'Back-End DM'
        - heroku container:login
 
      deploy:
        provider: heroku
        api_key: $HEROKU_TOKEN
        app: psique-dm
        script:
          - heroku container:push web -a psique-dm
          - heroku container:release web -a psique-dm
        on: 
          repo: Daniel0205/Psique-DM
          branch: feature/deployAPI