dist: xenial
os: linux
git:
  depth: 3 

language: node_js
node_js:
  - 14
services:
  - docker
jobs:
  include:
    # ======== Parte del frontend ========
    - language: node_js
      node_js:  '14'

      warnings_are_errors: false

      cache: 
        directories:
          - node_modules

      before_install: 
        - cd 'Back-End DM'
 
      deploy:
        provider: script
        app: psique-dm
        script:
          - heroku container:login
          - heroku container:push web -a psique-dm
          - heroku container:release web -a psique-dm
        on: 
          repo: Daniel0205/Psique-DM
          branch: feature/deployAPI