dist: xenial
os: linux
git:
  depth: 3 

language: node_js
node_js:
  - 12

jobs:
  include:
    # ======== Parte del frontend ========
    - language: node_js
      node_js:  '12'

      warnings_are_errors: false

      cache: 
        directories:
          - node_modules

      before_install: 
        - cd Back-End
        - CI=false 

      install:
        - npm install
        
      script:
        - npm run dev
      deploy:
        provider: heroku
        api_key: $HEROKU_TOKEN
        app: psique-dm
        on: 
          repo: Daniel0205/Psique-DM
          branch: feature/deployAPI